### ISSUE TITLE
 raise ImportError("libsixel not found.")

### ISSUE THREAD

**Issue by AHBkingman** [saitoha/libsixel#132]
I had tried installing libsixel using "pip install libsixel-python" and using python setup.py install after downloading the library. It was installed successively however when trying to import any thing from the library the following message appears 
"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\libsixel_python-0.5.1-py3.7.egg\libsixel\__init__.py", line 367, in <module>
    raise ImportError("libsixel not found.")
ImportError: libsixel not found." 
Knowing that I am using windows and Anaconda based.

**Comment by hysrx** [comment]
The module is merely a wrapper and you will have to install libsixel, the library. I recommend using the Windows Subsystem for Linux if you would want to proceed.

**Comment by saitoha** [comment]
While providing only the binding is not uncommon in the Python ecosystem, I regret that it has resulted in poor usability and has proven undesirable from a version management perspective.
Since it's likely possible to build libsixel within the setup script or take other approaches, I'll leave this issue open for now.

**Comment by ahgera** [comment]
There is no libsixel.dll available in the releases, so it seems that in order to use the Python library you also need to set up a C compiler and build the dll yourself. This isn't great for usability as you say, and I don't think building it in the setup script is a good idea since this won't work on most Windows environments. 

I think the best options are either include the binaries in a pre-built Python wheel, or publish binaries to winget and make it clear for the Python package users that they need to install that. Or at least publish a dll file here on Github.

**Comment by Kreijstal** [comment]
maybe create a msys2 package ?

**Comment by saitoha** [comment]
@ahgera 
> self contained wheels with all binary dependencies on PyPi would be a really good idea too. 

Thank you for the suggestion. I agreed on shipping self-contained wheels on PyPI.

But I lost access to my old PyPI account "saitoha" and password reset mail don’t arrive, so I can’t update the existing PyPl project. As a workaround I’ll publish under a new user/new package for now (and consider transferring/merging if I regain access).

Plan: build with cibuildwheel for Linux (manylinux2014 x86_64/aarch64), macOS (x86_64/arm64), and Windows (win_amd64). Use auditwheel / delocate / delvewheel to bundle binary dependencies so installs are system-independent at import time.

Timing: I’m currently deep in another refactor, so wheel releases will be later than I’d like. I do understand the importance of this issue and will share updates here as soon as I make progress.
If you have any suggestions for the package name or wheel build options, please let me know. Contributions or PRs would be very much appreciated.
