### ISSUE TITLE
Cant load library libsixel.so.1

### ISSUE THREAD

**Issue by hysrx** [saitoha/libsixel#138]
So I have tried `make`-ing the project and using the PyPi version, yet on both occasions I can't load the library. Could it be an incompatibility with Windows Subsystem for Linux 2, or PyPy, or the way I try to install this?

```python
Python 3.6.9 (2ad108f17bdb, Apr 07 2020, 02:59:05)
[PyPy 7.3.1 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> from libsixel.encoder import Encoder, SIXEL_OPTFLAG_WIDTH, SIXEL_OPTFLAG_COLORS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/src/virtualenvs/code-wXNkIn9M/site-packages/libsixel/__init__.py", line 355, in <module>
    _sixel = cdll.LoadLibrary(find_library('sixel'))
  File "/mnt/c/src/pypylinux/lib-python/3/ctypes/__init__.py", line 432, in LoadLibrary
    return self._dlltype(name)
  File "/mnt/c/src/pypylinux/lib-python/3/ctypes/__init__.py", line 350, in __init__
    pypy_dll = _ffi.CDLL(name, mode)
OSError: Cannot load library libsixel.so.1: libsixel.so.1: cannot open shared object file: No such file or directory
>>>>
```

**Comment by hysrx** [comment]
# Fix
After `make`ing, cd into `libsixel/src/.libs` and copy all files `usr/tmp`
